server:
  port: 9090

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9296

  cloud:
    gateway:
      mvc:
        routes:
          - id : ORDER-SERVICE
            uri: lb://ORDER-SERVICE
            predicates:
              - Path=/orders/**
#            filters:
#              - name: CircuitBreaker
#                args:
#                  name: ORDER-SERVICE
#                  fallbackuri: forward://orderServiceFallback
          - id: PAYMENT-SERVICE
            uri: lb://PAYMENT-SERVICE
            predicates:
              - Path=/payments/**
#            filters:
#              - name: CircuitBreaker
#                args:
#                  name: PAYMENT-SERVICE
#                  fallbackuri: forward://paymentServiceFallback
          - id: PRODUCT-SERVICE
            uri: lb://PRODUCT-SERVICE
            predicates:
              - Path=/products/**
#            filters:
#              - name: CircuitBreaker
#                args:
#                  name: PRODUCT-SERVICE
#                  fallbackuri: forward://productServiceFallback
okta:
  oauth2:
    issuer: https://dev-63084272.okta.com/oauth2/default
    audience: api://default
    client-id: 0oag3627g9OEEyGw85d7
    client-secret: 0RjfFLvMfTMkNkK2iMgMdeyyAIVvF1HxrFZumFaJhr2gStU892WI_BmPmVSVqVk1
    scopes: openid, profile, email, offline_access